### PR TITLE
[WFAPI-3182] Removing support for Ruby 2.2.1 and older

### PR DESCRIPTION
**Pull request by hannelita**

### CODE REVIEW

**Comment by adamcohen** [comment]
LGTM

**Comment by hannelita** [comment]
Hi, I am trying to fix the build with this PR. Turn out we have this test:


```ruby
# subscriber_spec.rb

# cannot use PubSub::Subscriber here because it would be evaluated before
# our overrides for Redlock below are processed
describe "PubSub::Subscriber" do
[...]
  describe '#subscribe' do
    it 'should work' do
      PubSub::Subscriber.subscribe
      ExampleUpdate.new(name: 'some name').publish
      expect(ExampleUpdate).to receive(:process) do
        raise NotImplementedError
      end
      expect do
        PubSub::Poller.new.poll
      end.to raise_error(NotImplementedError)
    end
  end
end
```

I’m really not sure about what it is testing. It breaks the suit because we can't simply call `PubSub::Subscriber.subscribe`, since it has a `send` on it. Any ideas on how to stub that?
\cc @adamcohen

**Comment by adamcohen** [comment]
@hannelita I noticed that test as well, it fails locally for me, but I thought it might have been something to do with my setup.  I looked at the failed build in Jenkins and it was due to the incorrect ruby version, and I wasn't able to see the output of the failed Travis build, so I couldn't verify that the issue was happening elsewhere.

In any case, I think we can get rid of that test since I'm not sure what it's testing either, as it seems to be making an actual live request.  I've tried stubbing out all the method calls, and ended up going down a rabbit hole with a huge number of mocks and expectations.

**Comment by hannelita** [comment]
@adamcohen yep, I tried several things as well. If you are curious, this is the failure, after removing the 2.2.1 build error:

```
Failure/Error: PubSub::Subscriber.subscribe
     Aws::Errors::MissingCredentialsError:
       unable to sign request without credentials set
```

Basically, the `before` config for `aws` does not work; possibly because we have a class method (`subscribe`) with a send.
We can open a ticket trying the following:
* testing the private methods of `subscribe.rb`;
* brainstorming a convenient way to stub `subscribe` class 
WDYT?

**Comment by hannelita** [comment]
@adamcohen  My point with this test is that it looks meaningless - expecting the rise of `NotImplementedError` does not look like a good way to test the subscribe function.

**Comment by adamcohen** [comment]
@hannelita The test was added in https://github.com/westfieldlabs/pub_sub/pull/61 and it passed jenkins at the time, so it looks like it did work at one point.  I'm not sure why it's stopped working. I've tried checking out the code from the last point where the tests were passing, and even tried changing all my gem versions to the same as Jenkins, and it still fails with the `Aws::Errors::MissingCredentialsError` error.

Apparently there are some stubs that can be used for testing AWS, there's some notes about it [here](https://stelligent.com/2016/04/14/using-stubs-for-the-aws-sdk-for-ruby-2), so this might be worth addressing in the future.

As it stands, it's very difficult to test the `PubSub::Subscriber` class since it's comprised of one single public method `self.subscribe` and 9 private methods, so we can't test each method in isolation.

I don't think we're losing much by removing this test, since it didn't work, and it's difficult to understand what it's doing, so it looks like it should be rewritten.  I've created [PEEPS-2553](https://jira.westfieldlabs.com/browse/PEEPS-2553) so we can track this requirement.

**Comment by adamcohen** [comment]
I'm curious though - why are the Jenkins tests still failing if the minimum ruby version has been changed to 2.2.2?

**Comment by hannelita** [comment]
@adamcohen It's Jenkins being naughty. It looks like we ran into this issue: https://issues.jenkins-ci.org/browse/JENKINS-33687 . See log:
```
New build name is '#112 17c75189'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#112 17c75189', new value: '#112 17c75189'
[ssh-agent] Stopped.
Collecting metadata...
```

**Comment by hannelita** [comment]
Jenkins fixed, I'll merge it @adamcohen @adbatista

**Pull request merged**
