### PR TITLE
[WFAPI-1895] Send machine of origin along with the message

### PR DESCRIPTION
**Pull request by emirkin**

### CODE REVIEW

**Comment by lucasrenan** [comment]
the travis build is broken :/

**Comment by emirkin** [comment]
That has nothing to do with my PR. Ops have not set up AWS correctly on Travis. I told them about it before.

**Comment by lucasrenan** [comment]
:+1:

**Comment by emirkin** [comment]
Tests succeed on any other machine.

**Comment by gwshaw** [comment]
whoami does not seem to return useful information on Heroku. It returns the name of the loggedin user, not the machine name:
```GeoMacBook-2:api.westfield.io george$ heroku run whoami -a centre-service-production
Running whoami on centre-service-production... up, run.6577

u34076```

A few services have the `HEROKU_APP_NAME` env var that contains a value like 'event-service-production'. If we made this standard, returning this value would be more useful. Note that when each service has individual API keys, the service could be derived from the key.

**Comment by emirkin** [comment]
@gwshaw This is purely for debugging purposes -- to look at it manually and understand where the message came from. `whoami` does that trick.

**Comment by gwshaw** [comment]
So getting 'u34076' is useful?

**Pull request merged**
